# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantmateApp.Plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantmateApp.UserProfile')),
            ],
        ),
    ]
