# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='hours',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='weekend_hours',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(default=' ', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='plant_slug',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_profile_images'),
        ),
    ]
