# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantmateApp', '0001_initial'),
    ]

