# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='room',
            field=models.CharField(choices=[('living-room/bedroom', 'Living-room/Bedroom'), ('kitchen/bathroom', 'Kitchen/Bathroom')], default='Living-room/Bedroom', max_length=128),
        ),
    ]
