# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='plant_images')),
            ],
        ),
    ]
