# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('saved_plant', models.CharField(default=' ', max_length=128)),
                ('wishlist_plant', models.CharField(default=' ', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plantmateApp.UserProfile')),
            ],
        ),
    ]
