# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_profile_images'),
        ),
    ]
