# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0002_auto_20190315_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='plant_slug',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
