# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0002_auto_20190315_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='business',
            name='weekend_hours',
        ),
        migrations.AddField(
            model_name='business',
            name='opening_hours',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
