# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
