# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0002_usersavedplants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWishlistPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_plant', models.CharField(default=' ', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantmateApp.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='usersavedplants',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usersavedplants',
            name='wishlist_plant',
        ),
        migrations.AlterField(
            model_name='usersavedplants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantmateApp.UserProfile'),
        ),
    ]
