# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0002_imageofplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageOfPlant',
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, upload_to='plant_images'),
        ),
    ]
