# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0003_auto_20190317_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
