# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0003_business_plant_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='room',
            field=models.CharField(choices=[('Living-room/Bedroom', 'living-room/bedroom'), ('Kitchen/Bathroom', 'kitchen/bathroom')], default='Living-room/Bedroom', max_length=128),
        ),
        migrations.AlterField(
            model_name='plant',
            name='climate',
            field=models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm')], default='cool', max_length=128),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('shady', 'Shady')], default='sunny', max_length=128),
        ),
    ]
