# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0004_auto_20190306_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantimage',
            old_name='image',
            new_name='picture',
        ),
    ]
