# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantmateApp', '0004_auto_20190308_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedplants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedplants',
            unique_together=set([('saved_plant', 'user')]),
        ),
    ]
