# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0005_auto_20190308_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_plant_images'),
        ),
    ]
