# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0005_auto_20190312_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='plant_slug',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
