# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0005_auto_20190306_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='url',
        ),
    ]
