# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0006_auto_20190318_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 16, 9, 51, 659936, tzinfo=utc), verbose_name='date published'),
        ),
    ]
