# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0006_remove_plantimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='name',
        ),
        migrations.AddField(
            model_name='plantimage',
            name='plant_name',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
