# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0007_auto_20190318_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
