# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantmateApp', '0008_auto_20190319_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
